<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checking_success_login_text</name>
   <tag></tag>
   <elementGuidId>55cfb782-e67e-48e4-98df-8a509db2e9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[2]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.login-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48f77dd1-5f51-44b1-a54d-4bd9e4f5db9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/tai-khoan</value>
      <webElementGuid>2d5dbb16-e4bc-4764-ae50-bce80199c4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-link</value>
      <webElementGuid>5be26426-509d-4887-9e2d-d285b9e9bdfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bao</value>
      <webElementGuid>f1cfc56b-b5f0-4662-8411-6af379c76138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-top bg-main hidden-xs&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;top-bar right&quot;]/ul[@class=&quot;horizontal-menu&quot;]/li[2]/a[@class=&quot;login-link&quot;]</value>
      <webElementGuid>7c691db9-5725-43cf-b84e-642e4d4d1ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>834fc410-7568-4181-911a-e32801e8c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'bao')]</value>
      <webElementGuid>f3119ac5-4ba5-4266-b4f7-1c68a6a8a8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Măng Cụt'])[1]/following::a[3]</value>
      <webElementGuid>80252c7c-202c-463d-8824-96e1a3da8a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sầu Riêng'])[1]/following::a[4]</value>
      <webElementGuid>51d5c796-157c-4576-9bd3-28f36ac53f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng xuất'])[1]/preceding::a[1]</value>
      <webElementGuid>2b050082-6981-4748-80f4-4ada0bd88a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang Chủ'])[2]/preceding::a[3]</value>
      <webElementGuid>567e41ac-2eb7-4168-9281-ad3f65184201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bao']/parent::*</value>
      <webElementGuid>b07b62b9-6775-4e9b-9963-c8b02d1e4728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/tai-khoan']</value>
      <webElementGuid>03711e92-0350-4042-b4b9-be78406d7544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>8466799c-699d-4be0-a643-c254eaf95ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/tai-khoan' and (text() = 'bao' or . = 'bao')]</value>
      <webElementGuid>d2cc9292-aa47-45d4-b9c7-5fc3ea6256d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
