<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_images</name>
   <tag></tag>
   <elementGuidId>99da67ad-f4fe-45e3-8f30-985f67d72c47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imageInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='imageInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bc3c0e7-eeaf-494c-8f9c-70337d633712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>33718647-fbab-4bdb-a309-ec13b22bf88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>images[]</value>
      <webElementGuid>bad894a1-2101-4201-af3f-d9044cbf9a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d81b5f75-6cfc-4ee6-a53d-83f66d4125ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imageInput</value>
      <webElementGuid>a8a97719-097b-4027-995b-2e08a19bdbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/jpg, image/jpeg, image/png, image/webp</value>
      <webElementGuid>8f17b82b-2db1-46f4-919f-743d4f7a91c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imageInput&quot;)</value>
      <webElementGuid>43359a6b-d1b9-4693-a1fc-65d9adc77a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='imageInput']</value>
      <webElementGuid>00f538f8-c7e5-4d97-ad0e-0698be4c2b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div/form/div[9]/input</value>
      <webElementGuid>b1d216d0-3316-4e5b-b0dc-3ccb29ed6368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>181297fc-92e3-4c93-8f5d-79304a72933a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'images[]' and @id = 'imageInput']</value>
      <webElementGuid>d3973650-3d3e-4507-a04b-2327b0575b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
