<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_TableOfDashBoard</name>
   <tag></tag>
   <elementGuidId>bdbb9475-af8a-4b7d-bae7-c698ef680b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsSvg1132</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Doanh số bán hàng'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>47ecb199-20ec-4c85-8de5-a46fab775436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SvgjsSvg1132</value>
      <webElementGuid>866f859e-4326-4c8b-a78a-328d7d61fbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1092</value>
      <webElementGuid>2739d384-d014-42a6-84f3-c0669a866f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>345</value>
      <webElementGuid>1eb9da6c-af29-4341-a603-d7a429fa8cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e695bce1-9fa8-49a4-9c6b-ef7cf37500a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>4a3aa82b-166e-4c1f-9ae2-6d4d66f6d912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>defe2117-08e1-4a2b-bc62-2b48db11d866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:svgjs</name>
      <type>Main</type>
      <value>http://svgjs.dev</value>
      <webElementGuid>771cbdaa-3941-4580-a895-0ad5f0b0704d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-svg</value>
      <webElementGuid>38972ea4-bf9c-44ae-9a92-4d02b89408d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:data</name>
      <type>Main</type>
      <value>ApexChartsNS</value>
      <webElementGuid>9afcfea5-8b40-48bc-9b17-d2268cf61f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-15, 0)</value>
      <webElementGuid>e3deb362-a7fa-4042-82f0-c37d760f0738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tháng 1Tháng 1Tháng 2Tháng 2Tháng 3Tháng 3Tháng 4Tháng 4Tháng 5Tháng 5Tháng 6Tháng 6Tháng 7Tháng 7Tháng 8Tháng 8Tháng 9Tháng 9Tháng 10Tháng 10Tháng 11Tháng 11Tháng 12Tháng 1296000096000072000072000048000048000024000024000000</value>
      <webElementGuid>c8df90a1-94de-4355-9691-a778be887dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsSvg1132&quot;)</value>
      <webElementGuid>41b40397-31c5-4ed6-ab2f-831addb80094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doanh số bán hàng'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d8e4b010-67d8-4070-bc28-ba2e6038b600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng doanh thu'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>10e741f4-ffce-4f5d-b98a-f3845811ee23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'SvgjsSvg1132' and (text() = 'Tháng 1Tháng 1Tháng 2Tháng 2Tháng 3Tháng 3Tháng 4Tháng 4Tháng 5Tháng 5Tháng 6Tháng 6Tháng 7Tháng 7Tháng 8Tháng 8Tháng 9Tháng 9Tháng 10Tháng 10Tháng 11Tháng 11Tháng 12Tháng 1296000096000072000072000048000048000024000024000000' or . = 'Tháng 1Tháng 1Tháng 2Tháng 2Tháng 3Tháng 3Tháng 4Tháng 4Tháng 5Tháng 5Tháng 6Tháng 6Tháng 7Tháng 7Tháng 8Tháng 8Tháng 9Tháng 9Tháng 10Tháng 10Tháng 11Tháng 11Tháng 12Tháng 1296000096000072000072000048000048000024000024000000')]</value>
      <webElementGuid>d8406511-0329-4612-bbfd-5187598529a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
