<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Check_out</name>
   <tag></tag>
   <elementGuidId>929bc48d-1b8d-41df-a4b9-0a4401e44e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.checkout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div/div[2]/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8eefc76c-25cc-4ce7-8df8-b18976defae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/dat-hang</value>
      <webElementGuid>0a8ea727-84e4-431b-89b9-d8f05577a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn checkout</value>
      <webElementGuid>e9217138-0a4e-4b51-9dd6-b9473154774d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh Toán</value>
      <webElementGuid>d22d6eca-9ad6-4dcd-8649-667252d48caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;shopping-cart-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;shpcart-subtotal-block&quot;]/div[@class=&quot;btn-checkout&quot;]/a[@class=&quot;btn checkout&quot;]</value>
      <webElementGuid>b791a703-cceb-470f-bd97-c76f8e117215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div/div[2]/div/div[4]/a</value>
      <webElementGuid>03fc691a-1d1b-4d4b-b206-fbb86c7d4671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thanh Toán')]</value>
      <webElementGuid>a9a2d1e9-b752-43d2-a46a-eaaab22f973c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh Toán:'])[1]/following::a[1]</value>
      <webElementGuid>a1927956-17a1-4d36-8d47-78ea7f384247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng Tiền'])[2]/following::a[1]</value>
      <webElementGuid>da7b0f88-029e-4149-8450-35222ed29d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Pickup'])[1]/preceding::a[1]</value>
      <webElementGuid>41b7ad19-f85d-430c-af0f-a74d59acceaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got Questions ?'])[1]/preceding::a[2]</value>
      <webElementGuid>a38239cc-cc96-4e5f-b117-5afeeb47cb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanh Toán']/parent::*</value>
      <webElementGuid>3c19d0cc-35b4-494f-8d13-0a90d2c9cabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/dat-hang']</value>
      <webElementGuid>1024b087-c958-4c2f-9fc8-a6f4247fc34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>9436285f-b385-4fb6-a513-ff67fb655d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/dat-hang' and (text() = 'Thanh Toán' or . = 'Thanh Toán')]</value>
      <webElementGuid>d2e0cc21-31e7-444e-95bd-2cab4c61825f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
