<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add cart</name>
   <tag></tag>
   <elementGuidId>a87e4453-6e6c-4878-8888-a2dc1d748475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.primary-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a6d9048-e817-4e2e-83a0-d2a5f94e0445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e0504d26-90d9-4313-8ad4-22a4335b0c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn</value>
      <webElementGuid>67466458-0190-4130-bd73-828c181fb986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Thêm vào giỏ hàng
                            </value>
      <webElementGuid>bf2de65f-13a0-4403-bb9b-9b164baeb171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;sumary-product single-layout&quot;]/div[@class=&quot;product-attribute&quot;]/form[1]/div[@class=&quot;action-form&quot;]/div[@class=&quot;buttons&quot;]/button[@class=&quot;primary-btn&quot;]</value>
      <webElementGuid>c9eebf38-9e58-4e91-bb79-da8f6253c76a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>ea1fdd46-07fd-4a3e-86c5-14cee13c0c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/form/div[2]/div[2]/button</value>
      <webElementGuid>faff25d1-98d2-49b8-b7b1-01418b4b362f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chính sách giao hàng'])[1]/following::button[1]</value>
      <webElementGuid>2228808c-fa86-4df9-838d-7be6ff532034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Tin Sản Phẩm'])[1]/preceding::button[1]</value>
      <webElementGuid>03c8be5a-323f-4e52-84dd-7db93e51943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chính Sách vận Chuyển'])[1]/preceding::button[1]</value>
      <webElementGuid>21c8b4d1-11a3-44e0-9896-2722a3f29b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thêm vào giỏ hàng']/parent::*</value>
      <webElementGuid>0d387a50-39b4-4511-94fb-f34bcd3330b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8752b144-8dfd-4221-a8c1-49a07b4fda21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                 Thêm vào giỏ hàng
                            ' or . = '
                                 Thêm vào giỏ hàng
                            ')]</value>
      <webElementGuid>8941c702-85e2-4613-8778-b70dc01e4c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
