<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_get_order</name>
   <tag></tag>
   <elementGuidId>ad6b001e-44fd-4fbe-9733-2fbe2399a576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-submit.btn-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>614ba816-f7a3-42d4-a6f5-50881c91cbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-submit btn-bold</value>
      <webElementGuid>d3220b6c-8f1b-4636-a973-5c6fd682b9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c7f0e983-9b49-499f-980b-82df22cd67a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh Toán</value>
      <webElementGuid>d694df69-c0be-4ab5-ab6d-26e225216fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container sm-margin-top-10px&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-md-5 col-sm-6 col-xs-12 sm-padding-top-48px sm-margin-bottom-0 xs-margin-bottom-15px&quot;]/div[@class=&quot;order-summary sm-margin-bottom-80px&quot;]/div[@class=&quot;cart-list-box short-type&quot;]/div[@class=&quot;form-row wrap-btn text-center&quot;]/button[@class=&quot;btn btn-submit btn-bold&quot;]</value>
      <webElementGuid>5f7bc61b-a5a6-4f11-bfde-b8c642aa1e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>00f2e3a7-18be-4881-bdb9-f31a358945e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>01121980-16f6-471f-b58a-be5e81e582bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Got Questions ?'])[1]/preceding::button[1]</value>
      <webElementGuid>fec41198-8f5f-4dd1-b644-de7cb3a4f946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter Signup'])[1]/preceding::button[1]</value>
      <webElementGuid>47fb8cd4-7edd-4191-ad25-45e9523f39a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>85df89ce-3805-4fe7-9c05-b15e4bbba97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Thanh Toán' or . = 'Thanh Toán')]</value>
      <webElementGuid>f149842c-708a-4d5e-b1cd-c4083932d0aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
