<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_using_cash</name>
   <tag></tag>
   <elementGuidId>8567927e-e9ee-4ff1-960b-1c9ba6db8c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div[2]/div/div[2]/ul[2]/li[3]/div/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba2d4116-f7fe-4e85-ba17-6eca28175679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>7380ac5b-cc8d-4482-83c4-7add94f05e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container sm-margin-top-10px&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-md-5 col-sm-6 col-xs-12 sm-padding-top-48px sm-margin-bottom-0 xs-margin-bottom-15px&quot;]/div[@class=&quot;order-summary sm-margin-bottom-80px&quot;]/div[@class=&quot;cart-list-box short-type&quot;]/ul[@class=&quot;subtotal&quot;]/li[3]/div[@class=&quot;subtotal-line&quot;]/div[@class=&quot;checkout__input__radio horizontal-radio&quot;]/label[1]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>bc685dfc-dd11-40c8-a4ef-9c6c7272d0f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[2]/div/div[2]/ul[2]/li[3]/div/div[2]/label/span</value>
      <webElementGuid>31acd1e1-1bb9-44c9-8311-34df1cf3c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/label/span</value>
      <webElementGuid>1d346081-d0bf-47ef-b29b-6b3e40ee57c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
