<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_check_selected</name>
   <tag></tag>
   <elementGuidId>83fb35f7-fc48-45a3-8f2f-454df2d52338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.badge.bg-dark.rounded-3.fw-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div/div/div/div/div/div[2]/table/tbody/tr/td[7]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5c6c001-8c4a-4aaf-91b2-d9669201d178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge bg-dark rounded-3 fw-semibold</value>
      <webElementGuid>5004376c-2e8d-4251-8f33-08f4961c48f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hủy đơn</value>
      <webElementGuid>3b38e089-2eba-49c6-8f31-ba1572efd62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card w-100&quot;]/div[@class=&quot;card-body p-4&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table text-nowrap mb-0 align-middle&quot;]/tbody[1]/tr[1]/td[@class=&quot;border-bottom-0 text-center&quot;]/span[@class=&quot;badge bg-dark rounded-3 fw-semibold&quot;]</value>
      <webElementGuid>d778f9cc-ba56-4e42-a96d-4876ce9589de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div/div/div[2]/table/tbody/tr/td[7]/span</value>
      <webElementGuid>c97b31bc-c77c-432e-9806-01bb8a33e597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#77'])[1]/following::span[1]</value>
      <webElementGuid>5823a066-79d7-46d9-83c0-62e4ae7bf711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hành động'])[1]/following::span[1]</value>
      <webElementGuid>9ab11584-47cf-441a-b6dc-c34bd34ee1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chi tiết'])[1]/preceding::span[1]</value>
      <webElementGuid>f5b70a3e-e727-42cd-bea8-e6140e4d4b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#73'])[1]/preceding::span[1]</value>
      <webElementGuid>0d56318c-3b4c-4e3a-83fa-611d382e575c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hủy đơn']/parent::*</value>
      <webElementGuid>d8210fda-f6ba-4cb4-a8cd-0484d8c90015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/span</value>
      <webElementGuid>3683b68e-8777-4993-bfff-8087cc846e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hủy đơn' or . = 'Hủy đơn')]</value>
      <webElementGuid>f8a1a2d5-eebf-4f8c-977c-77a9f44d337d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
