<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_update</name>
   <tag></tag>
   <elementGuidId>d6d0d25d-cdf5-4665-b2ff-966344b695b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fl-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff0b5f4c-06fd-4905-b794-a0598e4b3016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fl-message</value>
      <webElementGuid>d506aa29-5e9c-4e07-a6be-6d8f2b255ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cập nhật danh mục thành công.</value>
      <webElementGuid>64cae3bc-1833-487b-ad51-c5332f0ab059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fl-dark-mode&quot;]/div[@class=&quot;fl-main-container fl-no-cache&quot;]/div[@class=&quot;fl-flasher fl-success fl-container fl-show&quot;]/div[@class=&quot;fl-content&quot;]/div[2]/span[@class=&quot;fl-message&quot;]</value>
      <webElementGuid>917b6e3d-18eb-40a8-a64f-1075cded6c9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::span[1]</value>
      <webElementGuid>97191760-a6dd-401f-a109-5317d2593fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[10]/following::span[1]</value>
      <webElementGuid>901df5d4-121e-48c2-b0f4-edae2e7e0c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cập nhật danh mục thành công.']/parent::*</value>
      <webElementGuid>57931c3b-6897-4b8a-934f-818631ca1e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>d84fc3fd-3888-4d67-9b85-5cc81ee6ddda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cập nhật danh mục thành công.' or . = 'Cập nhật danh mục thành công.')]</value>
      <webElementGuid>5624c762-f0f6-4643-8a0c-2d66378adf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
