<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abutton_store</name>
   <tag></tag>
   <elementGuidId>cc6286a9-c73f-44fc-a9b2-5090a47a9ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='primary-menu']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#primary-menu > li.menu-item.menu-item-has-children > a.menu-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f48c27d-d364-48f7-a2fc-acc312933764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/cua-hang</value>
      <webElementGuid>6ceaaf62-9155-4ca7-b333-494334145d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-name</value>
      <webElementGuid>a3bc83d7-d79e-4701-bbf3-04b4110e30de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>31a304aa-2f2e-451c-a5b2-2e43cd22b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cửa hàng</value>
      <webElementGuid>523e3938-00b9-4774-a5b5-224e1cf9b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-menu&quot;)/li[@class=&quot;menu-item menu-item-has-children&quot;]/a[@class=&quot;menu-name&quot;]</value>
      <webElementGuid>5bf54cf5-0913-41be-a488-bca670ca5246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-menu']/li[2]/a</value>
      <webElementGuid>1ff50e5a-0ccf-45ea-9540-b47bdc67b27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cửa hàng')])[2]</value>
      <webElementGuid>2e941616-578a-4a62-a14d-ee76337c3a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang Chủ'])[2]/following::a[1]</value>
      <webElementGuid>4ead28a6-f68f-4078-9be1-ee43dabb7b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[1]/following::a[3]</value>
      <webElementGuid>3a6cd55f-e005-4e42-9d0c-2199a43f8c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Về chúng tôi'])[2]/preceding::a[1]</value>
      <webElementGuid>7396e8fa-9375-420f-ba22-1c1dc76bd884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liên hệ'])[2]/preceding::a[2]</value>
      <webElementGuid>99fb2872-8ce4-4491-b495-8d634e516148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://127.0.0.1:8000/cua-hang'])[2]</value>
      <webElementGuid>49b445b7-1018-4505-a9a7-721f78d42efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>e69c10b1-e03b-4dc3-9745-cc6a5d9d2831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/cua-hang' and (text() = 'Cửa hàng' or . = 'Cửa hàng')]</value>
      <webElementGuid>8b551880-9422-4b5a-bd94-99dd790ea159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
