<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_cart</name>
   <tag></tag>
   <elementGuidId>5efd9c8a-4d1a-49c0-a4a1-4c57d63c65dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div/div/table/tbody/tr/td/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.prd-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04907e4f-8031-45e2-a865-fcde9a80a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prd-name</value>
      <webElementGuid>47de4749-36fc-4f06-8794-6380680d5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d8f29de3-6cb3-4e6b-9d2a-108324ac7b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TH Truemilk update</value>
      <webElementGuid>371eb80c-fb5a-42a3-b207-6ad6139114cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;shopping-cart-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-md-12 col-sm-12 col-xs-12&quot;]/table[@class=&quot;shop_table cart-form&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-thumbnail&quot;]/a[@class=&quot;prd-name&quot;]</value>
      <webElementGuid>bf60e031-ed48-4e79-b08b-8fb794ae3b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div/div/table/tbody/tr/td/a[2]</value>
      <webElementGuid>17079adc-5858-4381-8118-46686765915e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TH Truemilk update')]</value>
      <webElementGuid>9fb0ea80-a233-4392-a21c-8e3a0a6ba47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng Tiền'])[1]/following::a[2]</value>
      <webElementGuid>7f0a9020-93e0-4084-9038-d4fd20453e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số Lượng'])[1]/following::a[2]</value>
      <webElementGuid>a2a81804-947a-48af-839a-1c709c77d3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp Tục Mua Hàng'])[1]/preceding::a[4]</value>
      <webElementGuid>e49fd707-7e7b-4400-8cd0-24e4a2adc64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Tin Thanh Toán'])[1]/preceding::a[5]</value>
      <webElementGuid>dba3a9e0-448e-4ff1-9043-7f227de9ff5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TH Truemilk update']/parent::*</value>
      <webElementGuid>7be52688-015e-4341-aae9-18d3e6509dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>dac2372a-4840-4288-abca-75376e6dced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a[2]</value>
      <webElementGuid>2f1f9251-8329-46e6-a478-e63ba45f7749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'TH Truemilk update' or . = 'TH Truemilk update')]</value>
      <webElementGuid>19d87527-acb5-4749-894c-ca5327288239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
