<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_year</name>
   <tag></tag>
   <elementGuidId>a6cce118-9c51-43ce-9a8a-9cefcbe07ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;year&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f405c0d1-0d71-4538-ab78-1a579791c336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>d5247f27-6b65-4e03-ae71-2844492329b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>673f33cb-c7e1-4633-9c9e-d1d00c426135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>9538031f-ed62-4697-993d-8e544764b13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                                                        2024
                                                                                                                    2023
                                                                                                                    2022
                                                                                                                    2021
                                                                                                                    2020
                                                                                                                    2019
                                                                    </value>
      <webElementGuid>470df607-33c1-4658-a043-ba92df3da807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 d-flex align-items-strech&quot;]/div[@class=&quot;card w-100&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-sm-flex d-block align-items-center justify-content-between mb-9&quot;]/form[1]/div[@class=&quot;d-flex align-items-center&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>adc44183-a5fd-495e-90e6-63209111d454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='year']</value>
      <webElementGuid>b79ed0f7-948c-4d18-a94f-133ca9c8ca9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/div/div/div[2]/div/div/div/form/div/select[2]</value>
      <webElementGuid>5e37f1b4-22e8-48f3-a244-b3c2d3732e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doanh số bán hàng'])[1]/following::select[2]</value>
      <webElementGuid>00f1d7f7-f34f-4a44-a5a0-0c887f0d9beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng doanh thu'])[1]/following::select[2]</value>
      <webElementGuid>a5a02ca1-dde2-4ac0-bcce-7af481cfe8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/preceding::select[1]</value>
      <webElementGuid>3e85582f-a033-40ad-940d-5cc2734d9e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download SVG'])[1]/preceding::select[1]</value>
      <webElementGuid>e35d385b-e5dc-4d4d-a3f1-8a6325ef8b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>632a9778-9e0a-4563-83bf-390f63df8694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'year' and (text() = '
                                                                                                                                                        2024
                                                                                                                    2023
                                                                                                                    2022
                                                                                                                    2021
                                                                                                                    2020
                                                                                                                    2019
                                                                    ' or . = '
                                                                                                                                                        2024
                                                                                                                    2023
                                                                                                                    2022
                                                                                                                    2021
                                                                                                                    2020
                                                                                                                    2019
                                                                    ')]</value>
      <webElementGuid>400757fb-279e-4429-ac3c-56f81022d515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
