<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_check</name>
   <tag></tag>
   <elementGuidId>0654cb7d-e5ac-421f-9095-10fc23879796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsTspan1468</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='0.0']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>a626bb77-129a-428f-8095-735109e53539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SvgjsTspan1468</value>
      <webElementGuid>e2c419fc-529b-4de6-b47a-325cbbef1249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>ec517f49-cc2c-4695-adb6-71368811b616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsTspan1468&quot;)</value>
      <webElementGuid>ffaeb571-9854-4d1e-8e86-dc94cf3068e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.0']/parent::*</value>
      <webElementGuid>0bd7fd82-280f-4e94-b6cb-27de4abfc79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[@id = 'SvgjsTspan1468' and (text() = '0.0' or . = '0.0')]</value>
      <webElementGuid>d30405c5-b1c5-48ce-8db9-c5d6fb99d9d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
