<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_30000</name>
   <tag></tag>
   <elementGuidId>93219f7c-40f1-4083-bd16-3ec49c0398e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SvgjsTspan1456</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='30000']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
      <webElementGuid>639883d3-398c-4e2b-bb25-da1ff7780451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SvgjsTspan1456</value>
      <webElementGuid>e0c80f0b-68f1-43e6-83e7-978e0c042555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30000</value>
      <webElementGuid>82db3955-5b81-454a-95e9-4633daa4179a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SvgjsTspan1456&quot;)</value>
      <webElementGuid>90f9d964-b46e-49ad-8756-2552a35c58b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30000']/parent::*</value>
      <webElementGuid>fab7f767-c205-4bf7-9fff-6e21cd952563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tspan[@id = 'SvgjsTspan1456' and (text() = '30000' or . = '30000')]</value>
      <webElementGuid>f8b8445d-89d3-4258-a2db-8f1b7a869b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
